services:
  front:
    working_dir: /app
    build:
      context: .
      dockerfile: production.Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network
networks:
  app-network:
    external: true

